'use strict';

/**
 * Shared vocabulary for the whole backend.
 * Keeping every enum in one place stops routes, services and the database
 * from drifting apart.
 */

const ROLES = Object.freeze({
  HOSPITAL: 'HOSPITAL',
  SUPPLIER: 'SUPPLIER',
  DELIVERY: 'DELIVERY',
  ADMIN: 'ADMIN',
});

const ORGANIZATION_TYPES = Object.freeze({
  HOSPITAL: 'HOSPITAL',
  PHARMACY: 'PHARMACY',
  SUPPLIER: 'SUPPLIER',
});

const VERIFICATION_STATUS = Object.freeze({
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
  SUSPENDED: 'SUSPENDED',
});

const ORDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PREPARING: 'PREPARING',
  DISPATCHED: 'DISPATCHED',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
});

const PRIORITY = Object.freeze({
  CRITICAL: 'CRITICAL',
  URGENT: 'URGENT',
  NORMAL: 'NORMAL',
});

const RESERVATION_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  CONSUMED: 'CONSUMED',
  RELEASED: 'RELEASED',
  EXPIRED: 'EXPIRED',
});

const DELIVERY_STATUS = Object.freeze({
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
});

const ITEM_TYPES = Object.freeze({
  MEDICINE: 'MEDICINE',
  EQUIPMENT: 'EQUIPMENT',
});

const EQUIPMENT_CONDITION = Object.freeze({
  NEW: 'NEW',
  GOOD: 'GOOD',
  REFURBISHED: 'REFURBISHED',
  NEEDS_SERVICE: 'NEEDS_SERVICE',
});

const STOCK_FRESHNESS = Object.freeze({
  FRESH: 'FRESH',
  RECENT: 'RECENT',
  STALE: 'STALE',
});

const NOTIFICATION_TYPES = Object.freeze({
  VERIFICATION_APPROVED: 'VERIFICATION_APPROVED',
  VERIFICATION_REJECTED: 'VERIFICATION_REJECTED',
  VERIFICATION_SUSPENDED: 'VERIFICATION_SUSPENDED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_ACCEPTED: 'ORDER_ACCEPTED',
  ORDER_DISPATCHED: 'ORDER_DISPATCHED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  EMERGENCY_REQUEST: 'EMERGENCY_REQUEST',
  LOW_STOCK: 'LOW_STOCK',
  EXPIRING_SOON: 'EXPIRING_SOON',
});

const AUDIT_ACTIONS = Object.freeze({
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  ORGANIZATION_CREATED: 'ORGANIZATION_CREATED',
  ORGANIZATION_APPROVED: 'ORGANIZATION_APPROVED',
  ORGANIZATION_REJECTED: 'ORGANIZATION_REJECTED',
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  DOCUMENT_SUBMITTED: 'DOCUMENT_SUBMITTED',
  MEDICINE_CREATED: 'MEDICINE_CREATED',
  EQUIPMENT_CREATED: 'EQUIPMENT_CREATED',
  INVENTORY_CREATED: 'INVENTORY_CREATED',
  INVENTORY_UPDATED: 'INVENTORY_UPDATED',
  INVENTORY_DELETED: 'INVENTORY_DELETED',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_RELEASED: 'RESERVATION_RELEASED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_CHANGED: 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  DELIVERY_CREATED: 'DELIVERY_CREATED',
  DELIVERY_STATUS_CHANGED: 'DELIVERY_STATUS_CHANGED',
});

/**
 * Allowed order status transitions.
 * Anything not listed here is rejected by the order service, so
 * DELIVERED -> PREPARING can never happen by accident.
 */
const ORDER_STATUS_TRANSITIONS = Object.freeze({
  PENDING: ['ACCEPTED', 'CANCELLED'],
  ACCEPTED: ['PREPARING', 'CANCELLED'],
  PREPARING: ['DISPATCHED', 'CANCELLED'],
  DISPATCHED: ['OUT_FOR_DELIVERY', 'CANCELLED'],
  OUT_FOR_DELIVERY: ['DELIVERED', 'CANCELLED'],
  DELIVERED: [],
  CANCELLED: [],
});

const DELIVERY_STATUS_TRANSITIONS = Object.freeze({
  ASSIGNED: ['PICKED_UP', 'FAILED'],
  PICKED_UP: ['IN_TRANSIT', 'FAILED'],
  IN_TRANSIT: ['DELIVERED', 'FAILED'],
  DELIVERED: [],
  FAILED: [],
});

/**
 * Which role is allowed to move an order into a given status.
 * ADMIN is allowed everywhere and is handled separately.
 */
const ORDER_STATUS_ACTORS = Object.freeze({
  ACCEPTED: [ROLES.SUPPLIER],
  PREPARING: [ROLES.SUPPLIER],
  DISPATCHED: [ROLES.SUPPLIER],
  OUT_FOR_DELIVERY: [ROLES.SUPPLIER, ROLES.DELIVERY],
  DELIVERED: [ROLES.DELIVERY, ROLES.HOSPITAL, ROLES.SUPPLIER],
  CANCELLED: [ROLES.HOSPITAL, ROLES.SUPPLIER],
});

/** Machine readable error codes returned to the frontend. */
const ERROR_CODES = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  ORGANIZATION_NOT_VERIFIED: 'ORGANIZATION_NOT_VERIFIED',
  INVENTORY_NOT_AVAILABLE: 'INVENTORY_NOT_AVAILABLE',
  RESERVATION_EXPIRED: 'RESERVATION_EXPIRED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  DATABASE_ERROR: 'DATABASE_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
});

/** Tables, so a typo becomes a crash at startup instead of an empty result. */
const TABLES = Object.freeze({
  PROFILES: 'profiles',
  ORGANIZATIONS: 'organizations',
  VERIFICATION_DOCUMENTS: 'verification_documents',
  MEDICINES: 'medicines',
  EQUIPMENT: 'equipment',
  INVENTORY: 'inventory',
  ORDERS: 'orders',
  ORDER_ITEMS: 'order_items',
  RESERVATIONS: 'reservations',
  DELIVERIES: 'deliveries',
  NOTIFICATIONS: 'notifications',
  AUDIT_LOGS: 'audit_logs',
});

module.exports = {
  ROLES,
  ORGANIZATION_TYPES,
  VERIFICATION_STATUS,
  ORDER_STATUS,
  PRIORITY,
  RESERVATION_STATUS,
  DELIVERY_STATUS,
  ITEM_TYPES,
  EQUIPMENT_CONDITION,
  STOCK_FRESHNESS,
  NOTIFICATION_TYPES,
  AUDIT_ACTIONS,
  ORDER_STATUS_TRANSITIONS,
  DELIVERY_STATUS_TRANSITIONS,
  ORDER_STATUS_ACTORS,
  ERROR_CODES,
  TABLES,
};
